FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

COPY ./*.sh /usr/src/app/
RUN chmod +x /usr/src/app/*.sh

COPY grafana.ini /usr/src/app/

RUN install_packages \
      fontconfig-config \
      fonts-dejavu-core \
      libfontconfig1 \
      ucf \
      jq \
      wget

RUN /usr/src/app/download.sh "%%BALENA_ARCH%%"

RUN dpkg -i /tmp/grafana.deb && rm /tmp/grafana.deb

CMD ["/bin/sh","/usr/src/app/entry.sh"]
